### ISSUE TITLE
Incremental API

### ISSUE THREAD

**Issue by bk2204** [mcarpenter/twofish.rb#6]
I'm implementing a PasswordSafe v3 export for my password tool, [daniel](https://github.com/bk2204/daniel).  The PasswordSafe v3 format uses CBC, but Twofish#encrypt resets the IV each time, which prevents using it incrementally (and is insecure if the same IV is used for multiple messages).  I therefore have to buffer all the data and then write it out at once.

Is it possible that an incremental API could be developed?

**Comment by mcarpenter** [comment]
> PasswordSafe v3 export

Ha, that's funny -- that's exactly why I wrote it in the first place (and I have some working code somewhere; it might not be fantastic but I can certainly share that... assuming I can find it).

> Twofish#encrypt resets the IV each time

Ahh, I see what you mean. You are creating a fresh `Twofish` instance midway through encoding some larger chunk of data? Would it be reasonable behavior to set `@iv` to the last generated ciphertext block in `Twofish#encrypt`? I'm not sure it would be: it would break "let's decrypt the thing I just encrypted". And it doesn't seem very intuitive.

A workaround is to take the last block of ciphertext and manually set that as the IV in the next `Twofish` instance. Here's a simple example, CBC encrypting just two blocks, first in one go and then in two steps with two `Twofish` instances:

    require 'twofish'

    key = ['9f589f5cf6122c32b6bfec2f2ae8c35a'].pack('H*').freeze
    iv = ['a74f3ed9a33ca158f3d09a629f9b26ba'].pack('H*').freeze
    plain = 'abcdefghijklmnopqrstuvwxyz123456'

    tf1 = Twofish.new(key, :iv => iv, :mode => :cbc)
    cipher = tf1.encrypt(plain)
    puts cipher.inspect

    tf1 = Twofish.new(key, :iv => iv, :mode => :cbc)
    cipher1 = tf1.encrypt(plain[0, Twofish::BLOCK_SIZE])
    tf2 = Twofish.new(key, :iv => cipher1, :mode => :cbc)
    cipher2 = tf2.encrypt(plain[Twofish::BLOCK_SIZE, Twofish::BLOCK_SIZE])
    puts (cipher1<< cipher2).inspect

=>

    "\xE1M\x0F\x03\n\xA8C\xB1Kai(\xA1\xC1\x8E\x8Bv\xC0\b\xAA'\x01]\xD2\e\xB7G\xA1\x87\x15\x17*"
    "\xE1M\x0F\x03\n\xA8C\xB1Kai(\xA1\xC1\x8E\x8Bv\xC0\b\xAA'\x01]\xD2\e\xB7G\xA1\x87\x15\x17*"

Perhaps this is good enough for what you're trying to do?

**Comment by mcarpenter** [comment]
Oh, and your [daniel](https://github.com/bk2204/daniel) repo is 404 (or maybe private?).

**Comment by bk2204** [comment]
What I basically want to is do something like the following:
```ruby
data = ['abcdefghijklmnop', '1234567890123456']
output = ''
tf = Twofish.new(key, :iv => iv, :mode => :cbc)
data.each { |s| output << tf.encrypt(s) }
```
And have output be encrypted iteratively; i.e., not with the same IV.

My experience writing and using crypto algorithms is that they tend to be stateful; that is, if you want to encrypt, then decrypt, you need a new object (or you need to reset the IV), since generally people want to use algorithms incrementally (online).  I think updating the @iv value is exactly what I'd expect.

What I'm doing now is https://github.com/bk2204/daniel-ruby/blob/master/lib/daniel/export/pwsafe.rb#L49, which is a bit suboptimal.

**Comment by mcarpenter** [comment]
data.each { |s| output << (tf.iv = tf.encrypt(s)) }

But I take your point. Not intuitive.

I think this will have to be a breaking change (for those that muddled their way to the solution above). Or I could mess around in `#iv=` (meh).

I'll think a little more and push out something tomorrow.

**Comment by mcarpenter** [comment]
Please see [1.0.6-dev](https://github.com/mcarpenter/twofish.rb/commits/1.0.6-dev) branch and two new [unit tests](https://github.com/mcarpenter/twofish.rb/blob/1.0.6-dev/test/test_twofish.rb#L173-L191).

**Comment by bk2204** [comment]
This works very well, thanks.

**Comment by mcarpenter** [comment]
Thanks, 1.0.6 pushed.
