### ISSUE TITLE
Twofish monkey-patches String to add force_encoding and breaks json gem in Ruby 1.8

### ISSUE THREAD

**Issue by bk2204** [mcarpenter/twofish.rb#7]
The `json` gem has code like the following:

```ruby
          if string.respond_to?(:force_encoding)
            string.force_encoding(::Encoding::UTF_8)
          end
```

If I load the `twofish` gem as well in Ruby 1.8, it defines force_encoding, and then the JSON parser throws an exception because `::Encoding` isn't defined. So basically, my software can't parse JSON if I load the twofish gem.

I'm going to send a pull request shortly which fixes this issue by using a helper function.

**Comment by mcarpenter** [comment]
Thanks!

Merged, pushed and published as 1.0.7.
